### PR TITLE
Whitelist import paths

### PR DESCRIPTION
**Pull request by ThibautBorn**
Add option to whitelist paths to import

### CODE REVIEW

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
I did not try it, but it LGTM. Do try to add tests though. A lot of corner cases or combinations are being checked already, so you should be able to find a similar test case to copy and edit. I did not check if `EXCLUDE_PATHS` is already tested.

I would say though that you should be able to combine this:

```
INCLUDE_PATHS = [`/Plone/documents`]
EXCLUDE_PATHS = [`/Plone/documents/archive`]
```

This should include all items in the documents folder, except in the archive sub folder.

But this could be tricky. What if for some reason you have the reverse?

```
EXCLUDE_PATHS = [`/Plone/documents`]
INCLUDE_PATHS = [`/Plone/documents/archive`]
```

This might just need a few lines of documentation specifying how we treat these two options. Something like this:

> We first check `EXCLUDE_PATHS`. If one of these paths matches the current item path, we exclude it. Only if it is not excluded, do we check `INCLUDE_PATHS`.

This then needs a one line change in your code:

```
- if self.INCLUDE_PATHS:
+ if self.INCLUDE_PATHS and not skip:
```

We could do a bit of validation once and warn when `INCLUDE_PATHS` contains a path that will never be included because it is already covered by `EXCLUDE_PATHS`.

**Comment by gotcha** [comment]
@pbauer This PR was waiting for comments since 2 months. Your commit 5f5f0bf does avoid it to be merged. How should we proceed ?

**Comment by pbauer** [comment]
Ups. I saw that PR a couple of months ago when I really needed that to work and just copied some code adapting it as I went along. Now I tried to push all useful changes I did in the last months and forgot about this pull-request. I'm really sorry for that, I don't want to block your work.  
We should at least add the tests. I also like the idea with the the small methods should_drop and so on. Would you mind updating this pull-request so that it works against the current main?

**Comment by gotcha** [comment]
@pbauer Just updated. Would you merge ? Or I do it myself ?

**Comment by pbauer** [comment]
Thanks!

**Comment by gotcha** [comment]
Thanks

**Pull request merged**
