### PR TITLE
Portal localroles

### PR DESCRIPTION
**Pull request by ThibautBorn**
adding migration of localroles set on portal/siteroot level

### CODE REVIEW

**Comment by ThibautBorn** [comment]
This branch is ready to review, our tests have been updated and are working

**Review by petschki — CHANGES_REQUESTED** [review]
possible development leftover, otherwise LGTM!

**Comment by gotcha** [comment]
@pbauer Anything that avoids this PR to being merged ? And released ?

**Review by petschki — APPROVED** [review]
👍🏼

**Review by pbauer — APPROVED** [review]

**Pull request merged**
