### PR TITLE
Fix HTML summary, message and counts

### PR DESCRIPTION
**Pull request by Rudd-O**

### CODE REVIEW

**Comment by pbauer** [comment]
Nice change to get the number of changed items. Could you also add a basic test for that feature?

**Review by Arhell — APPROVED** [review]

**Comment by Rudd-O** [comment]
> Nice change to get the number of changed items. Could you also add a basic test for that feature?

Will do!

**Comment by Rudd-O** [comment]
I'm very confused and I could use some help.   Why is my test failing but only for Python 2.7???

**Comment by mauritsvanrees** [comment]
Looking at the [html output](https://github.com/collective/collective.exportimport/runs/4697148244?check_suite_focus=true#step:7:702) of the 2.7 test, the displayed portal status message is "Fixed HTML for 0 fields in content items. Fixed HTML for 0 portlets." So nothing got fixed.

One problem I see in the test, is that you create rich text values with output mimetype [`text/x/html-safe`](https://github.com/collective/collective.exportimport/pull/96/files#diff-2ca41ae287a4bb939702053ea1238c763c313079d252b32a7d629f81fb084e4cR1013) instead of `text/x-html-safe`. Maybe this is fine on Python 3, but trips up 2.7? Just a guess.

If that does not help, try it locally on 2.7 and add a `pdb` in `fix_html_in_content_fields` and run the test.

Or in the test check what `doc2.text.raw` is after calling the html fixer. Maybe it got fixed after all and it contains `resolveuid`, but the report somehow misses it.

**Comment by pbauer** [comment]
I have added some tests to fix_html with https://github.com/collective/collective.exportimport/pull/98 maybe your test can piggy-back on these.

**Comment by Rudd-O** [comment]
> Looking at the html output of the 2.7 test, the displayed portal status message is "Fixed HTML for 0 fields in content items. Fixed HTML for 0 portlets." So nothing got fixed.

But the tests for py36 work correctly.  So what's going on?

**Comment by pbauer** [comment]
I suggest you run the tests locally in py2 and add a pdb where fix_html decides if something got fixed or not.

**Comment by Rudd-O** [comment]
@pbauer thanks for the suggestion — just saw your comment.  If this run does not work, I will have to figure out how to do a py2 local build env.  Pointers more than welcome.

**Comment by pbauer** [comment]
I often use pyenv and pyenv virtualenv (https://github.com/pyenv/pyenv-virtualenv) to manage all kings of python versions and switch between them:

```
pyenv virtualenv 2.7.18 exportimport-py2
pyenv local exportimport-py2
pip install -r requirements.txt
buildout
```

**Comment by Rudd-O** [comment]
What's missing for the merge?

**Comment by gotcha** [comment]
@Rudd-O I feel it would make sense to merge/squash some of your commits. What do you think ?

**Pull request merged**
