### PR TITLE
Log items that cannot be deserialized

### PR DESCRIPTION
**Pull request by mikejmets**
Working with the importer I had difficulty identifying which items could not be deserialized so I now trap the error, log the item details and raise it.

### CODE REVIEW

**Comment by fredvd** [comment]
@mikejmets We can expose deserialisation error better in a show while.  the problem is that plone.restapi by default masks/catches all detailed validation exceptions to a simple ValidationError and reraises.  My patch to disable this based on a parameter we call the method has been accepted and has beenr released in 8.11.0.  But it needs to be backported to the latest stable 7 version of plone.restapi as well before we can depend on it in collective.exportimport.

this is an improvement on top of the logging you add here, I think both will help a lot with debugging content import issues.

**Comment by mikejmets** [comment]
Thanks @fredvd

**Comment by mikejmets** [comment]
I resisted the temptation to resolve black and flake8 issues to keep the PR simple/easy to read

**Comment by pbauer** [comment]
The same feature was added by #57

**Pull request closed without merging**
