### PR TITLE
Use db.storage instead of connection._storage

### PR DESCRIPTION
**Pull request by gotcha**
to take care of connection wrapped in a temp storage

### CODE REVIEW

**Comment by pbauer** [comment]
I recently had the same issue. But even in Plone 4.3 `db._storage`is only there for "Backward compatibility". 
So I suggest using `db.storage`

**Comment by gotcha** [comment]
> I recently had the same issue. But even in Plone 4.3 `db._storage`is only there for "Backward compatibility". So I suggest using `db.storage`

I missed that. I rebased with your change.

**Comment by gotcha** [comment]
@pbauer Please do not merge until we check that the problem we had before @ale-rt fix is actually fixed.

**Comment by gotcha** [comment]
@pbauer Ready to merge from our side.

And a new release would be great...

**Pull request merged**
