### PR TITLE
Fix the <source> / <iframe> tags too, and unify tag fix handling.

### PR DESCRIPTION
**Pull request by Rudd-O**
Merry Christmas!  This PR simplifies the HTML tag fixer, and also ensures that the `<source>` tags are `resolveuid`'d too.

Counterpart of https://github.com/plone/plone.app.linkintegrity/pull/83

### CODE REVIEW

**Comment by Rudd-O** [comment]
Related question:

I would like to discover where / what in the Plone codebase Plone transforms links to `resolveuid/%s`  form before save.  If that does not exist, I would love to know how to create a transform that is invoked prior to saving, so that I can apply a logic similar to this PR's whenever I save my content types.

Any pointers?

**Comment by Rudd-O** [comment]
Related: https://github.com/plone/plone.outputfilters/pull/47

**Comment by Rudd-O** [comment]
@jenkins-plone-org please run jobs

**Comment by Rudd-O** [comment]
I will add tests once the same test code used in https://github.com/collective/collective.exportimport/pull/96 is merged so that I don't have to resolve a merge conflict unnecessarily.

**Comment by Rudd-O** [comment]
I have resolved the merge conflict issue, and added tests which pass completely in my local test environment.

**Comment by Rudd-O** [comment]
Tests passed!

**Comment by mauritsvanrees** [comment]
There is a conflict in `fix_html.py`. Can you rebase on master, or merge master into your branch?

**Pull request merged**
