### PR TITLE
Fix import content Decimal json.dumps 

### PR DESCRIPTION
**Pull request by avoinea**
- refs #212

### CODE REVIEW

**Comment by pbauer** [comment]
I'll wait until the py27 jobs are fixed. @gotcha is working on that in https://github.com/collective/collective.exportimport/pull/214

**Comment by gotcha** [comment]
@pbauer @avoinea Can you check #213 as another way to avoid the Decimal json issue ?

**Comment by pbauer** [comment]
Closing in favour of #213.
@avoinea Does that work for you?

**Comment by avoinea** [comment]
@pbauer We'll see :wink:

**Pull request closed without merging**
