### PR TITLE
Enable more custom views

### PR DESCRIPTION
**Pull request by ThibautBorn**

### CODE REVIEW

**Comment by Rudd-O** [comment]
What's the goal of the PR, in more detail?  I'm curious.

**Comment by ThibautBorn** [comment]
I'm working on a large migration of multiple sites, which we want to automate. So instead of using the webinterface, we're calling the migration script through the code. While doing this we noticed some inconveniences, that made it difficult to call/override certain functions. So these are some minor changes/restructuring so users can acces these methods, without needing to call the view.

**Comment by Rudd-O** [comment]
Would love to see some code using them, I am doing the exact same you are doing.

**Review by mauritsvanrees — APPROVED** [review]
Seems okay.

**Comment by gotcha** [comment]
@pbauer Philipp, what is your preferred process for this repo ? Should we merge ourselves or nudge you to do it ?

**Pull request merged**
